### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by sadboi-drip** [jejellyroll-fr/fpdb-3#5]
When loading the hand viewer for SwC Poker the loader hangs halfway and gives the following error when checking the log: `parser - ERROR - Hand - end - Pot.end(): '0': Major failure while calculating pot: 'list index out of range' Pot.end(): '%s': Major failure while calculating pot: '%s' 0 list index out of range`. I am unable to tell which hand is causing the issue but I ran across this error 
`Traceback (most recent call last):
  File "/home/xxx/fpdb-3/Hand.py", line 1941, in end
    v1 = commitslive[0][0]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/xxx/fpdb-3/GuiHandViewer.py", line 154, in loadHands
    self.reload_hands(hand_ids)
  File "/home/xxx/fpdb-3/GuiHandViewer.py", line 198, in reload_hands
    self.hands[handid] = self.importhand(handid)
  File "/home/xxx/fpdb-3/GuiHandViewer.py", line 326, in importhand
    h = Hand.hand_factory(handid, self.config, self.db)
  File "/home/xxx/fpdb-3/Hand.py", line 1987, in hand_factory
    hand_instance.select(db_connection, hand_id)
  File "/home/xxx/fpdb-3/Hand.py", line 579, in select
    self.totalPot()
  File "/home/xxx/fpdb-3/Hand.py", line 913, in totalPot
    self.pot.end()
  File "/home/xxx/fpdb-3/Hand.py", line 1947, in end
    raise FpdbParseError
Exceptions.FpdbParseError: ''
Traceback (most recent call last):
  File "/home/xxx/fpdb-3/Hand.py", line 1941, in end
    v1 = commitslive[0][0]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/xxx/fpdb-3/GuiHandViewer.py", line 154, in loadHands
    self.reload_hands(hand_ids)
  File "/home/xxx/fpdb-3/GuiHandViewer.py", line 198, in reload_hands
    self.hands[handid] = self.importhand(handid)
  File "/home/xxx/fpdb-3/GuiHandViewer.py", line 326, in importhand
    h = Hand.hand_factory(handid, self.config, self.db)
  File "/home/xxx/fpdb-3/Hand.py", line 1987, in hand_factory
    hand_instance.select(db_connection, hand_id)
  File "/home/xxx/fpdb-3/Hand.py", line 579, in select
    self.totalPot()
  File "/home/xxx/fpdb-3/Hand.py", line 913, in totalPotparser - ERROR - Hand - end - Pot.end(): '0': Major failure while calculating pot: 'list index out of range'
Pot.end(): '%s': Major failure while calculating pot: '%s' 0 list index out of range
    self.pot.end()
  File "/home/xxx/fpdb-3/Hand.py", line 1947, in end
    raise FpdbParseError
Exceptions.FpdbParseError: ''`

**Comment by sadboi-drip** [comment]
I am using Fedora 40

**Comment by jejellyroll-fr** [comment]
ok, i will check, can you share in private all hands(by mail for example: jejellyroll.fr@gmail.com ), it will be more easy to debug

**Comment by jejellyroll-fr** [comment]
hello, i made a fix, for your issue on the newui-mini on the branch but i recommand to use web version for data viz and replaying on the newui-mini

tell me if the fix, is working for you and application does not crash anymore

**Comment by jejellyroll-fr** [comment]
FIXED
